const CHANGE_IS_LOGIN = 'CHANGE_IS_LOGIN';

const CHANGE_TOKEN = 'CHANGE_TOKEN';

const CHANGE_NAME = 'CHANGE_NAME';

const CHANGE_ROLE = 'CHANGE_ROLE';

export { CHANGE_IS_LOGIN, CHANGE_TOKEN, CHANGE_NAME, CHANGE_ROLE };
