export const CREATE_SPECIALIZATION = 'CREATE_SPECIALIZATION';

export const SET_ALL_SPECIALIZATION = 'SET_ALL_SPECIALIZATION';

export const UPDATE_SPECIALIZATION = 'UPDATE_SPECIALIZATION';

export const CHANGE_ACTIVE_SPECIALIZATION = 'CHANGE_ACTIVE_SPECIALIZATION';
